/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.au;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.lang.WordUtils;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static String capitaliseMessage(String args) throws Exception{

        System.out.println("standard message : " + args);

        String capitalised_result = WordUtils.capitalizeFully(args);

        return capitalised_result;

    }
    public static void main(String[] args) throws Exception {
        Option msg = Option.builder("m")
                .longOpt("message")
                .hasArg()
                .desc("the message to capitalize")
                .build();
        Options options = new Options();
        options.addOption(msg);

        CommandLineParser parser = new DefaultParser();
        CommandLine line = parser.parse(options, args);

        String  message = line.getOptionValue("m", "Hello Ivy!");
        String result = capitaliseMessage(message);
        System.out.println("capitalized by " + WordUtils.class.getName()
                + " : " + WordUtils.capitalizeFully(result));
    }
}
